worker_processes  1;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    server {
        listen 8083;
        server_name localhost;

        location / {
            root html/enduser;
            index index.html index.htm;
            try_files $uri $uri/ index.html;
        }

        # This block enables proxying to OpenIDM running on localhost:8080

        location /openidm {
            proxy_pass http://localhost:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}