export default {
  _id: 'contractorOnboarding:7:25005',
  _rev: '1',
  category: 'Examples',
  deleted: false,
  deploymentId: '25001',
  derivedFrom: null,
  derivedFromRoot: null,
  derivedVersion: 0,
  description: null,
  engineVersion: null,
  graphicalNotationDefined: true,
  hasStartFormKey: true,
  historyLevel: null,
  idPrefix: 'PRC-',
  inserted: true,
  ioSpecification: null,
  isGraphicalNotationDefined: true,
  key: 'contractorOnboarding',
  localizedDescription: null,
  localizedName: null,
  name: 'Contractor onboarding process',
  processDiagramResourceName: 'contractorOnboarding.contractorOnboarding.png',
  resourceName: 'contractorOnboarding.bpmn20.xml',
  revisionNext: 2,
  suspended: false,
  suspensionState: 1,
  tenantId: '',
  updated: false,
  variables: null,
  version: 7,
  formResourceKey: 'contractorForm.js',
  formGenerationTemplate: "{\n    /*\n     * Copyright 2018-2025 Ping Identity Corporation. All Rights Reserved\n     */\n\n    name: 'Contractor-Onboarding-Start',\n\n    props: {\n        processDefinition: Object,\n        taskDefinition: Object,\n        variables: Object,\n        isTask: {\n            type: Object,\n            default: () => ({})\n        }\n    },\n\n    data() {\n        return {\n            formData: {}\n        };\n    },\n\n    computed: {\n        taskId() {\n            if (this.taskDefinition && this.taskDefinition._id) {\n                return this.taskDefinition._id;\n            }\n            return 'startEvent';\n        }\n    },\n\n    watch: {\n        formData: {\n            handler() {\n                return undefined;\n            },\n            deep: true\n        }\n    },\n\n    methods: {\n        setFormData() {\n            this.formData = this.processDefinition.formProperties.reduce((acc, formProperty) => {\n                const dataObject = {};\n\n                if (this.variables && this.variables[formProperty._id]) {\n                    dataObject[formProperty._id] = this.variables[formProperty._id];\n                } else {\n                    dataObject[formProperty._id] =\n                        formProperty.type.name === 'boolean' ? false : '';\n                }\n\n                return Object.assign(acc, dataObject);\n            }, {});\n        },\n\n        resetForm() {\n            this.$refs.observer.reset();\n            this.setFormData();\n        },\n\n        cancel() {\n            this.resetForm();\n            this.$emit('cancel');\n        },\n\n        submit() {\n            this.$refs.observer.validate().then((valid) => {\n                if (valid) {\n                    const payload = { ...this.formData };\n\n                    if (this.taskId === 'startEvent') {\n                        payload._processDefinitionId = this.processDefinition._id;\n                    }\n\n                    this.$emit('submit', payload);\n                }\n            });\n        },\n\n        accept() {\n            this.formData.decision = 'accept';\n            this.submit();\n        },\n\n        reject() {\n            this.formData.decision = 'reject';\n            this.submit();\n        },\n\n        addValidationProps(formProperty) {\n            return {\n                required: formProperty.required,\n                email: formProperty._id === 'mail',\n                numeric: formProperty._id === 'telephoneNumber',\n                date_format:\n                    formProperty._id === 'startDate' ||\n                    formProperty._id === 'endDate'\n            };\n        },\n\n        getValidationState({ dirty, validated, valid = null } = {}) {\n            return dirty || validated ? valid : null;\n        }\n    },\n\n    created() {\n        this.setFormData();\n    },\n\n    template: `\n        <ValidationObserver ref=\"observer\" slim>\n            <b-form class=\"w-100\" :name=\"processDefinition._id\">\n                <b-form-group\n                    v-for=\"formProperty in processDefinition.formProperties\"\n                    :key=\"formProperty._id\"\n                >\n                    <template v-if=\"formProperty.type.name === 'string'\">\n                        <ValidationProvider\n                            :rules=\"addValidationProps(formProperty)\"\n                            :name=\"formProperty.name\"\n                            #default=\"validationContext\"\n                        >\n                            <b-form-input\n                                :name=\"formProperty._id\"\n                                type=\"text\"\n                                v-model=\"formData[formProperty._id]\"\n                                :state=\"getValidationState(validationContext)\"\n                            />\n                            <b-form-invalid-feedback>\n                                {{ validationContext ? validationContext.errors[0] : undefined }}\n                            </b-form-invalid-feedback>\n                        </ValidationProvider>\n                    </template>\n\n                    <template v-else-if=\"formProperty.type.name === 'boolean'\">\n                        <b-form-checkbox\n                            switch\n                            size=\"lg\"\n                            class=\"mt-1 fr-toggle-primary\"\n                            v-model=\"formData[formProperty._id]\"\n                        />\n                    </template>\n\n                    <template #label>\n                        {{ formProperty.name }}\n                        <small\n                            v-if=\"!formProperty.required\"\n                            class=\"text-muted ml-1\"\n                        >\n                            {{ $t('pages.profile.editProfile.optional') }}\n                        </small>\n                    </template>\n                </b-form-group>\n\n                <b-form-group class=\"form-group row justify-content-end\">\n                    <template v-if=\"taskId !== 'startEvent'\">\n                        <div class=\"col text-right\">\n                            <b-button\n                                variant=\"outline-danger\"\n                                @click=\"reject\"\n                            >\n                                Reject\n                            </b-button>\n                            <b-button\n                                variant=\"primary\"\n                                @click=\"accept\"\n                            >\n                                Accept\n                            </b-button>\n                        </div>\n                    </template>\n\n                    <template v-else>\n                        <div class=\"col text-right\">\n                            <b-button\n                                variant=\"outline-secondary\"\n                                @click=\"cancel\"\n                            >\n                                Cancel\n                            </b-button>\n                            <b-button\n                                variant=\"primary\"\n                                @click=\"submit\"\n                            >\n                                Submit\n                            </b-button>\n                        </div>\n                    </template>\n                </b-form-group>\n            </b-form>\n        </ValidationObserver>\n    `\n}",
  formProperties: [
    {
      readable: true,
      variableName: null,
      defaultExpression: null,
      name: 'Username',
      _id: 'userName',
      type: {
        datePattern: null,
        values: null,
        name: 'string',
      },
      variableExpression: null,
      required: true,
      writable: true,
    },
    {
      readable: true,
      variableName: null,
      defaultExpression: null,
      name: 'First Name',
      _id: 'givenName',
      type: {
        datePattern: null,
        values: null,
        name: 'string',
      },
      variableExpression: null,
      required: true,
      writable: true,
    },
    {
      readable: true,
      variableName: null,
      defaultExpression: null,
      name: 'Last Name',
      _id: 'sn',
      type: {
        datePattern: null,
        values: null,
        name: 'string',
      },
      variableExpression: null,
      required: true,
      writable: true,
    },
    {
      readable: true,
      variableName: null,
      defaultExpression: null,
      name: 'Department',
      _id: 'department',
      type: {
        datePattern: null,
        values: null,
        name: 'string',
      },
      variableExpression: null,
      required: false,
      writable: true,
    },
    {
      readable: true,
      variableName: null,
      defaultExpression: null,
      name: 'Job Title',
      _id: 'jobTitle',
      type: {
        datePattern: null,
        values: null,
        name: 'string',
      },
      variableExpression: null,
      required: false,
      writable: true,
    },
    {
      readable: true,
      variableName: null,
      defaultExpression: null,
      name: 'Phone Number',
      _id: 'telephoneNumber',
      type: {
        datePattern: null,
        values: null,
        name: 'string',
      },
      variableExpression: null,
      required: true,
      writable: true,
    },
    {
      readable: true,
      variableName: null,
      defaultExpression: null,
      name: 'Email',
      _id: 'mail',
      type: {
        datePattern: null,
        values: null,
        name: 'string',
      },
      variableExpression: null,
      required: true,
      writable: true,
    },
    {
      readable: true,
      variableName: null,
      defaultExpression: null,
      name: 'Start Date',
      _id: 'startDate',
      type: {
        datePattern: null,
        values: null,
        name: 'string',
      },
      variableExpression: null,
      required: true,
      writable: true,
    },
    {
      readable: true,
      variableName: null,
      defaultExpression: null,
      name: 'End Date',
      _id: 'endDate',
      type: {
        datePattern: null,
        values: null,
        name: 'string',
      },
      variableExpression: null,
      required: false,
      writable: true,
    },
    {
      readable: true,
      variableName: null,
      defaultExpression: null,
      name: 'Description',
      _id: 'description',
      type: {
        datePattern: null,
        values: null,
        name: 'string',
      },
      variableExpression: null,
      required: true,
      writable: true,
    },
    {
      readable: true,
      variableName: null,
      defaultExpression: null,
      name: 'Create in CSVFile',
      _id: 'provisionToCSV',
      type: {
        datePattern: null,
        values: null,
        name: 'boolean',
      },
      variableExpression: null,
      required: false,
      writable: true,
    },
  ],
};
