/**
 * Copyright (c) 2022-2025 ForgeRock. All rights reserved.
 *
 * This software may be modified and distributed under the terms
 * of the MIT license. See the LICENSE file for details.
 */

import MarkdownIt from 'markdown-it';
import markdownItAnchor from 'markdown-it-anchor';
import TurndownService from 'turndown';
import { pd } from 'pretty-data';
import { baseSanitizerConfig, sanitize } from './sanitizerConfig';

/**
 * constant used to insert a placeholder in the cleanHtml function
 */
const cleaningPlaceholder = '{{fr-breakline}}';

/**
 * Replaces the '<br>' tags in an html string with a placeholder string.
 * The purpose of this function is to avoid undesired behavior with the <br> tag
 * when converting html to markdown using Turndown.
 * @param {string} html html to be cleaned
 * @returns {string} cleanedHtml
 */
function protectSpecialCharacters(html) {
  return html.replace(new RegExp('</?br */?>', 'gi'), cleaningPlaceholder);
}

/**
 * Restoring means replacing the placeholder strings introduced in the cleanHtml function with the original values.
 * '\n' is changed to ' ' by the markdown converter; this function reverts that change.
 * @param {string} markdown that needs to be restored
 * @returns {string} the restored markdown string
 */
function restoreSpecialCharacters(markdown) {
  if (markdown === '') return markdown;
  const changes = [
    { pattern: `${cleaningPlaceholder} `, flags: ['g'], change: '<br>\n' },
    { pattern: `${cleaningPlaceholder}`, flags: ['g'], change: '<br>' },
  ];
  return changes.reduce((current, { pattern, flags, change }) => current.replace(new RegExp(pattern, flags.join('')), change), markdown);
}

/**
 * Parses the HTML generated by the markdown converter and wraps the content in a div element with class "content"
 * @param {string} html The HTML content string previously generated by tghe markdown converter
 * @returns {string} The string representing the HTML content wrapped in a div element with a "content" class
 */
export function wrapContent(html) {
  const domparser = new DOMParser();
  const doc = domparser.parseFromString(html, 'text/html');
  const hasContentDiv = doc.getElementsByClassName('content').length > 0;

  if (hasContentDiv) {
    return pd.xmlmin(html);
  }

  const contentDiv = `<div class="content">${doc.body.innerHTML}</div>`;
  doc.body.innerHTML = contentDiv;

  return pd.xmlmin(doc.body.innerHTML);
}

/**
 * Extracts the innerHTML contained in a div element with class "content" from an HTML document
 * @param {string} content HTML document containing a div element with a class "content"
 * @returns The innerHTML inside of the div with class "content"
 */
export function getContentChildren(content) {
  const domparser = new DOMParser();
  const doc = domparser.parseFromString(content, 'text/html');
  const contentDiv = doc.getElementsByClassName('content');
  const hasContentDiv = contentDiv.length > 0;
  return hasContentDiv ? contentDiv[0].innerHTML : content;
}

/**
 * Converts an HTML document into a markdown document.
 * @param {string} html HTML document in string format that can be converted to regular markdown.
 * @returns {string} A markdown document as string.
 */
export function html2Markdown(html) {
  const content = getContentChildren(html);
  const protectedHtml = protectSpecialCharacters(content);
  const turndownService = new TurndownService();
  const markdown = turndownService.turndown(protectedHtml);
  return restoreSpecialCharacters(markdown);
}

/**
 * Converts markdown content into HTML.
 * @param {string} markdown Markdown text to be transformed into HTML.
 * @param {boolean} wrapInDivContent If true, the markdown content will be converted to HTML and wrapped in a div with class "content".
 * @returns {string} HTML resulting from the conversion of the markdown document.
 */
export function markdown2Html(markdown, wrapInDivContent) {
  const md = new MarkdownIt({ html: true, typographer: true }).use(markdownItAnchor, {
    level: 1, // Minimum header level to apply anchors (default: 1)
    tabIndex: false, // Disable tabIndex on heading
    slugify: (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, ''), // Custom ID generator
  });

  let html = md.render(String(markdown));
  html = sanitize(html, baseSanitizerConfig);
  return wrapInDivContent ? wrapContent(html) : html;
}

/**
 * Takes a markdown document with some CSS styles and combines them together to create a full HTML document with its corresponding styles for a preview in an iframe container
 * @param {string} markdown Markdown text to be transformed into HTML
 * @param {string} styles Styles represented in CSS format to be applied to the resulting HTML document
 * @returns {string} Full HTML string with styles applied resulted from the convertion of the Markdown document to HTML
 */
export function markdown2HtmlPreview(markdown, styles) {
  const wrapedHtml = markdown2Html(markdown, true);
  const parsedHtml = `<style>${styles}</style>${wrapedHtml}`;
  return sanitize(parsedHtml, baseSanitizerConfig);
}
